### ISSUE TITLE
More Random Plz!

### ISSUE THREAD

**Issue by wackyMole** [wackyMole/wotd#1]
```php
if (!$word && $word = $wordRepository->findOneBy(['date' => null])) {
    $word->setDate(new \DateTime());

    $entityManager->flush();
}
```

Instead of just grabbing the first result where `date` is `NULL`, the result should be a random selection from all records where `date` is `NULL`.

**Comment by dannyweeks** [comment]
Doctrine does't support the `RAND` function it is possible indirectly. I have implemented on[ a branch](https://github.com/dannyweeks/wotd/blob/more-randomness/src/AppBundle/Repository/WordRepository.php#L15).

This would still have room to grow for when voting is introduced and and would be a good starting block for #5.

What do you think?

**Comment by wackyMole** [comment]
Thanks again @dannyweeks
