### ISSUE TITLE
Mis-match between documented PHP version and composer lock 

### ISSUE THREAD

**Issue by dannyweeks** [wackyMole/wotd#10]
Readme file says `PHP >= 5.5.9` but the composer.lock file dictates PHP 7.1 is required. Would you want to move to 7.1 or still support 5.5.9?

```

  Problem 1
    - Installation request for doctrine/annotations v1.5.0 -> satisfiable by doctrine/annotations[v1.5.0].
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (5.6.17) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/cache v1.7.0 -> satisfiable by doctrine/cache[v1.7.0].
    - doctrine/cache v1.7.0 requires php ~7.1 -> your PHP version (5.6.17) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/collections v1.5.0 -> satisfiable by doctrine/collections[v1.5.0].
    - doctrine/collections v1.5.0 requires php ^7.1 -> your PHP version (5.6.17) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.17) does not satisfy that requirement.
  Problem 5
    - Installation request for twig/twig v2.4.3 -> satisfiable by twig/twig[v2.4.3].
    - twig/twig v2.4.3 requires php ^7.0 -> your PHP version (5.6.17) does not satisfy that requirement.
  Problem 6
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (5.6.17) does not satisfy that requirement.
    - doctrine/common v2.7.3 requires doctrine/annotations 1.* -> satisfiable by doctrine/annotations[v1.5.0].
    - Installation request for doctrine/common v2.7.3 -> satisfiable by doctrine/common[v2.7.3].
```

**Comment by wackyMole** [comment]
This was printed on `composer install`?

**Comment by wackyMole** [comment]
The `composer.json` and `composer.lock` in this project specifies PHP >= 5.5.9. However, there are a few dependencies that require >= 7.0 and three of them require 7.1.

Let's bump the requirement to PHP 7.1. I'm not interested in supporting the app on an EOL version of PHP and I never planned on supporting 5.5.9. It was a default value that I never got around to updating.

**Comment by wackyMole** [comment]
So basically:

* [ ] Update PHP version in `composer.json` to `~7.1`
* [ ] Run `composer update --lock` to regenerate the `composer.lock` file without updating other dependencies.
* [ ] Update the "Requirements" section in `README.md` to "PHP >= 7.1" (remove the `(for now)` part)

**Comment by dannyweeks** [comment]
Yes this was on a composer install. Your suggestion to bump to 7.1 seems reasonable!

**Comment by ruchit288** [comment]
@dannyweeks
Yes, you have to update your current php version 5.5 to 7.1 at least to fulfill the required dependencies.
I have already faced this issue, at that time I just updated my php version and updating my composer files and it works.
