### ISSUE TITLE
No way to exit impersonation on smaller screens

### ISSUE THREAD

**Issue by wackymole** [wackymole/wotd#2]
Below a certain size, the footer disappears. The Copyright information moves to the bottom of the menu, but the exit impersonation link does not.

**Comment by wackyMole** [comment]
Need to copy the `{% if is_granted('ROLE_PREVIOUS_ADMIN') %}` statement in `app/resources/views/base.html.twig` (line 181 ish) and paste it in the top navbar, after the "Logout" `li` (line 139 ish) and add the `hidden-lg hidden-md` classes to the `li` inside of the `if` statement.

That should make the "Stop Impersonating" `li` appear in the drop-down menu on small screens, and leave it in the footer on large and medium screens.

**Comment by alaskaa** [comment]
Could I give this a try? I've only made two pull requests so far and this seems like a good issue to practice with and become familiar with contributions.

**Comment by wackyMole** [comment]
Absolutely @alaskaa! If you need help, let me know.

**Comment by alaskaa** [comment]
Just as a heads up, still working on this :) should get it finished in the next two days :)
